"""The other implementation's output, opened by this one.

`summareader/docs/protocol-vectors.json` is generated by that repo's
`tool/protocol_vectors.dart`. If these pass, this port agrees with the app
about the envelope, the key derivation and the record format. If they fail,
it does not — and every one of those disagreements is otherwise silent,
showing up as a library that syncs cleanly and contains nothing.
"""

from __future__ import annotations

import base64
import json
import os
from pathlib import Path

import pytest

from summareader_mcp.protocol import (
    KeyPurpose,
    LogOp,
    LogRecord,
    SealedBlob,
    SyncKeys,
    blob_name,
    open_text,
    source_of,
    subkey,
)
from summareader_mcp.protocol.envelope import seal_text

VECTORS = Path(
    os.environ.get(
        "SUMMAREADER_VECTORS",
        Path(__file__).resolve().parents[2] / "summareader" / "docs" / "protocol-vectors.json",
    )
)


@pytest.fixture(scope="module")
def vectors() -> dict:
    if not VECTORS.exists():
        pytest.skip(
            f"no vectors at {VECTORS}; generate with "
            "`dart run tool/protocol_vectors.dart` in the summareader repo"
        )
    return json.loads(VECTORS.read_text())


@pytest.fixture(scope="module")
def master(vectors) -> bytes:
    return base64.b64decode(vectors["masterKey"])


def test_every_subkey_matches(vectors, master):
    """The five purposes, byte for byte.

    A mistyped info string is the cheapest way to make an entire library
    unreadable while everything appears to work.
    """
    for purpose, expected in vectors["subkeys"].items():
        assert base64.b64encode(subkey(master, purpose)).decode() == expected, purpose


def test_the_purposes_are_spelled_allreader():
    # Not a tautology: the app was renamed, and "fixing" these strings is the
    # obvious tidy-up that would break every existing log.
    assert KeyPurpose.LOG_ENTRIES == "allreader/v1/log"
    assert KeyPurpose.BLOB_CONTENTS == "allreader/v1/blob"
    assert KeyPurpose.BLOB_NAMES == "allreader/v1/name"


def test_every_record_opens(vectors, master):
    keys = SyncKeys.derive(master)
    for entry in vectors["records"]:
        opened = open_text(SealedBlob.from_wire(entry["sealed"]), keys.log_entries)
        assert opened == entry["plaintext"], entry["op"]


def test_every_record_decodes_to_its_op(vectors, master):
    keys = SyncKeys.derive(master)
    for entry in vectors["records"]:
        record = LogRecord.decode(
            open_text(SealedBlob.from_wire(entry["sealed"]), keys.log_entries)
        )
        assert record is not None, entry["op"]
        assert record.op == entry["op"]


def test_an_unknown_op_is_readable_but_not_known(vectors, master):
    """Skipped, not failed. It is what makes the format extensible."""
    keys = SyncKeys.derive(master)
    unknown = [e for e in vectors["records"] if e["op"] not in LogOp.KNOWN]
    assert unknown, "the vectors should carry an op from a newer version"
    for entry in unknown:
        record = LogRecord.decode(
            open_text(SealedBlob.from_wire(entry["sealed"]), keys.log_entries)
        )
        assert record is not None and not record.known


def test_the_item_record_has_a_title_and_no_source(vectors, master):
    """The whole bug, as a test.

    `title` is under `data`. `source` does not exist — it is the first
    non-saved membership. Reading either at the top level gives None, which is
    what shipped.
    """
    keys = SyncKeys.derive(master)
    entry = next(e for e in vectors["records"] if e["op"] == LogOp.ITEM)
    record = LogRecord.decode(
        open_text(SealedBlob.from_wire(entry["sealed"]), keys.log_entries)
    )

    assert record.data["title"] == "Vědci objevili vypínač imunity"
    assert "source" not in record.data
    assert source_of(record) == "A Feed"


def test_a_channel_without_a_title_falls_back_to_its_address(vectors, master):
    keys = SyncKeys.derive(master)
    entry = next(e for e in vectors["records"] if e["op"] == LogOp.ITEM)
    record = LogRecord.decode(
        open_text(SealedBlob.from_wire(entry["sealed"]), keys.log_entries)
    )

    from summareader_mcp.protocol.records import channel_name, channels_of

    nameless = channels_of(record)[1]
    assert "title" not in nameless
    assert channel_name(nameless) == "https://other.example/feed"


def test_blob_names_match(vectors, master):
    keys = SyncKeys.derive(master)
    for sample, expected in vectors["blobNames"].items():
        assert blob_name(sample.encode("utf-8"), keys.blob_names) == expected, sample


def test_we_can_seal_something_the_same_way(master):
    """Round-trips through our own code.

    The vectors prove we can read theirs; this proves the writing half agrees
    with the reading half, which is what makes a failure above mean "the format
    is wrong" rather than "our opener is wrong".
    """
    keys = SyncKeys.derive(master)
    record = LogRecord(op=LogOp.READ, id="abc", data={"read": True})
    assert (
        open_text(seal_text(record.encode(), keys.log_entries), keys.log_entries)
        == record.encode()
    )


def test_rubbish_is_none_rather_than_an_exception():
    # One unreadable entry must not stop a sync.
    keys = SyncKeys.derive(bytes(range(32)))
    for wire in ("", "not-an-envelope", "a.b", "!!!.!!!.!!!", "a.b.c.d"):
        assert open_text(SealedBlob.from_wire(wire), keys.log_entries) is None
